

spring:
  data:
    mongodb:
      uri: mongodb+srv://kandpaldipesh_db_user:dipesh123@cluster0.lejnf2u.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true




  mail:
    host: smtp.gmail.com
    port: 587
    username: chota4885@gmail.com
    password: puradhlwfzidegvz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  redis:
    host: suitable-beautiful-head-30637.db.redis.io
    port: 18961
    username: default
    password: f6fYVYviBVWkI3hblWnYYF5ZHJZ1THwc

server:
  port: 9090
  servlet:
    context-path: /journal

logging:
  level:
     net:
      edigest:
        JournalAppNewest: INFO

weather:
  api:
    key: 4ccdfeb1ed49cc27798d355807658baf



