spring:
  profiles:
    active: dev


server:
  port: 9090
  servlet:
    context-path: /journal

logging:
  level:
    net:
      edigest:
        JournalAppNewest: INFO

weather:
  api:
    key: 4ccdfeb1ed49cc27798d355807658baf