spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: kandpaldipesh@gmail.com
    password: xgrr tvkr jkpe qewe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 9090
  servlet:
    context-path: /journal

logging:
  level:
    net:
      edigest:
        JournalAppNewest: INFO

weather:
  api:
    key: 4ccdfeb1ed49cc27798d355807658baf